#  前后端直接在docker中运行compose.yaml文件



version: "3.9"

services:
  # -----------------------
  # PostgreSQL (长期记忆)
  # -----------------------
  postgres:
    image: postgres:16-alpine  # 使用 alpine 版本，更小
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-agent_store}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # 限制日志大小
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # 减小到 5MB
        max-file: "2"        # 只保留 2 个文件
    # 限制容器资源
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # -----------------------
  # etcd (Milvus metadata)
  # -----------------------
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=2147483648  # 减小到 2GB
      - ETCD_HEARTBEAT_INTERVAL=500
      - ETCD_ELECTION_TIMEOUT=2500
    command:
      - etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 256M

  # -----------------------
  # MinIO (Milvus segment storage)
  # -----------------------
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 512M

  # -----------------------
  # Milvus 向量数据库
  # -----------------------
  milvus:
    image: milvusdb/milvus:latest
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 2G

  # -----------------------
  # Agent 后端主服务
  # -----------------------
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      # 禁用 Python 字节码缓存
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy
      milvus:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8080/info', timeout=5).raise_for_status()"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./privatecredentials:/privatecredentials:ro  # 只读挂载
      - sqlite_data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 1G

  # -----------------------
  # Streamlit 前端
  # -----------------------
  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service:8080
      - STREAMLIT_APP=${STREAMLIT_APP:-streamlit_app.py}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8501/healthz', timeout=5).raise_for_status()"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 512M
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py
        - path: src/arg_app.py
          action: sync+restart
          target: /app/arg_app.py

# -----------------------
# 持久化卷
# -----------------------
volumes:
  postgres_data:
  sqlite_data:
  milvus_data:
  etcd_data:
  minio_data:
